<?php /** @var $block \DIW\AWIN\Block\OrderConfirmation */ ?>
<?php if ($block->getAwinEnabled() && $block->getOrderId()) : ?>
<img src="<?= $block->escapeHtmlAttr($this->getAwinPixelUrl()) ?>" border="0" height="0" width="0" style="display: none;" />
<script type="text/javascript">
//<![CDATA[ /*** Do not change ***/
var AWIN = {};
AWIN.Tracking = {};
AWIN.Tracking.Sale = {};

/*** Set your transaction parameters ***/
AWIN.Tracking.Sale.amount = <?= json_encode((string)($block->getOrderSubtotal())); ?>;
AWIN.Tracking.Sale.orderRef = <?= json_encode((string)($block->getOrderId())); ?>;
AWIN.Tracking.Sale.parts = <?= json_encode((string)($block->getAwinCommissionGroup().':'.$block->getOrderSubtotal())); ?>;
AWIN.Tracking.Sale.voucher = <?= json_encode((string)($block->getOrderCouponCode())); ?>;
AWIN.Tracking.Sale.currency = <?= json_encode((string)($block->getOrderCurrencyCode())); ?>;
AWIN.Tracking.Sale.test = <?= json_encode((string)($block->getAwinIsTest() ? 1 : 0)); ?>;
AWIN.Tracking.Sale.channel = <?= json_encode((string)($block->getAwinChannel())); ?>;
//]]>;
</script>
<?php endif; ?>
